export enum Address {
  // EEPROM
  ModelNumber = 0,
  FirmwareWersion = 2,
  ID = 3,
  BoundRate = 4,
  ReturnDelatTime = 5,
  CWAngleLimit = 6,
  CWWAngleLimit = 8,
  TemperatureLimit = 11,
  MinVoltageLimit = 12,
  MaxVoltageLimit = 13,
  MaxTorque = 14,
  StatusReturnLevel = 16,
  AlarmLED = 17,
  Shutdown = 18,
  //RAM
  TorqueEnable = 24,
  LED = 25,
  CWComplianceMargin = 26,
  CCWComplianceMargin = 27,
  CWComplianceSlope = 28,
  CCWComplianceSlope = 29,
  GoalPosition = 30,
  MovingSpeed = 32,
  TorqueLimit = 34,
  PresentPosition = 36,
  PresentSpeed = 38,
  PresentLoad = 40,
  PresentVoltage = 42,
  PresentTemperature = 43,
  Registered = 44,
  Moving = 46,
  Lock = 47,
  Punch = 48,
}
